# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [7]:
# Create a 1-dimensional NumPy array using np.array()
d1 = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
d2 = np.random.randint(10, size=(2,3))

# Create a 3-dimensional Numpy array using np.array()
d3 = np.random.random((2,3,4))

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
d1.shape, d1.ndim, d1.dtype,d1.size, type(d1)

((5,), 1, dtype('int32'), 5, numpy.ndarray)

In [9]:
# Attributes of 2-dimensional array
d2.shape, d2.ndim, d2.dtype, d2.size, type(d2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
d3.shape, d3.ndim, d3.dtype, d3.size, type(d3)

((2, 3, 4), 3, dtype('float64'), 24, numpy.ndarray)

In [15]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd
df = pd.DataFrame(d2, columns=['a','b','c'])
df

a  b  c
0  6  2  1
1  7  1  7

In [22]:
# Create an array of shape (10, 2) with only ones
a1 = np.ones((10,2)); a1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
# Create an array of shape (7, 2, 3) of only zeros
a2 = np.zeros((7,2,3)); a2

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
# Create an array within a range of 0 and 100 with step 3
a3 = np.arange(0,100,3); a3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a4 = np.random.randint(0,10, size=(7,2)); a4

array([[8, 7],
       [1, 2],
       [2, 7],
       [8, 0],
       [0, 5],
       [5, 4],
       [7, 1]])

In [27]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a5 = np.random.random((3,5)); a5

array([[0.5562121 , 0.21469878, 0.46775923, 0.09073102, 0.32877822],
       [0.51198761, 0.25883721, 0.90571137, 0.95200145, 0.48169848],
       [0.45748714, 0.93362089, 0.98556875, 0.07172181, 0.25622678]])

In [30]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a6 = np.random.randint(0,10, size=(4,6)); a6

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?
: because we have set the seed to a constant no e.g 42 here which fixes the randomisation.

In [42]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a7 = np.random.randint(1,10,size=(3,7))
print(a7)
# Find the unique numbers in the array you just created
unique = np.unique(a7); unique

[[1 4 7 2 3 1 5]
 [1 8 1 1 2 2 6]
 [7 5 1 1 3 2 5]]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
# Find the 0'th index of the latest array you created
a7[0]

array([1, 4, 7, 2, 3, 1, 5])

In [43]:
# Get the first 2 rows of latest array you created
a7[:2]

array([[1, 4, 7, 2, 3, 1, 5],
       [1, 8, 1, 1, 2, 2, 6]])

In [45]:
# Get the first 2 values of the first 2 rows of the latest array
a7[:2, :2]

array([[1, 4],
       [1, 8]])

In [47]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a8 = np.random.randint(0,10,size=(3,5))
a9 = np.ones((3,5))

In [49]:
# Add the two arrays together
np.add(a8,a9)

array([[10.,  6.,  7.,  4.,  7.],
       [ 8.,  1.,  6.,  8.,  5.],
       [ 4.,  2.,  6.,  6.,  1.]])

In [51]:
# Create another array of ones of shape (5, 3)
a10 = np.ones((5,3)); a10

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
# Try add the array of ones and the other most recent array together
np.add(a10,a9)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?
: because boradcasting rules says either dimension match or should be equal to one

How would you fix it? : by reshaping one of the arrays

In [56]:
a11 = a10.reshape(5,3)

In [57]:
#now we can add:
np.add(a11, a10)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [59]:
# Create another array of ones of shape (3, 5)
a12 = np.ones((3,5))

In [63]:
# Subtract the new array of ones from the other most recent array
np.subtract(a12,a10.reshape(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
# Multiply the ones array with the latest array
a8 * a12

array([[9., 5., 6., 3., 6.],
       [7., 0., 5., 7., 4.],
       [3., 1., 5., 5., 0.]])

In [66]:
# Take the latest array to the power of 2 using '**'
a8 ** 2

array([[81, 25, 36,  9, 36],
       [49,  0, 25, 49, 16],
       [ 9,  1, 25, 25,  0]], dtype=int32)

In [67]:
# Do the same thing with np.square()
np.square(a8)

array([[81, 25, 36,  9, 36],
       [49,  0, 25, 49, 16],
       [ 9,  1, 25, 25,  0]], dtype=int32)

In [68]:
# Find the mean of the latest array using
np.mean(a8)

4.4

In [69]:
# Find the maximum of the latest array
np.max(a8)

9

In [71]:
# Find the minimum of the latest array
np.min(a8)

0

In [72]:
# Find the standard deviation of the latest array
np.std(a8)

2.524546163834865

In [73]:
# Find the variance of the latest array
np.var(a8)

6.373333333333334

In [75]:
# Reshape the latest array to (3, 5, 1)
a8.reshape(3,5,1)

array([[[9],
        [5],
        [6],
        [3],
        [6]],

       [[7],
        [0],
        [5],
        [7],
        [4]],

       [[3],
        [1],
        [5],
        [5],
        [0]]])

In [76]:
# Transpose the latest array
a8.T

array([[9, 7, 3],
       [5, 0, 1],
       [6, 5, 5],
       [3, 7, 5],
       [6, 4, 0]])

What does the transpose do? : It switches the axes

In [77]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
b1 = np.random.randint(0,10,size=(3,3))
b2 = np.random.randint(0,10, size=(3,3))

In [78]:
# Perform a dot product on the two newest arrays you created
np.dot(b1, b2)

array([[76, 50, 73],
       [45, 20, 44],
       [55, 56, 55]])

In [3]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
b3 = np.random.randint(0,10,size=(4,3))
b4 = np.random.randint(0,10,size=(4,3))

In [4]:
# Perform a dot product on the two newest arrays you created
np.dot(b3, b4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [5]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

np.dot(b3, b4.T)

array([[ 64, 110,  93,  25],
       [ 46, 103,  94,  41],
       [ 41,  61,  90,  47],
       [ 42,  88, 104,  56]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [44]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables

c1 = np.random.randint(0,10,size=(3,4))
c2 = np.random.randint(0,10,size=(3,4))

In [45]:
# Compare the two arrays with '>'
c1 > c2

array([[False,  True,  True, False],
       [False, False,  True, False],
       [False, False,  True,  True]])

What happens when you compare the arrays with `>`? : It compares each element of two arrays who are in same position.

In [46]:
# Compare the two arrays with '>='
c1 >= c2

array([[False,  True,  True, False],
       [False, False,  True, False],
       [ True, False,  True,  True]])

In [47]:
# Find which elements of the first array are greater than 7
c1 > 7  #where there's True, the element is greater than 7

array([[False,  True, False, False],
       [False, False, False, False],
       [ True, False, False,  True]])

In [48]:
# Which parts of each array are equal? (try using '==')
c1 == c2  #where there's True, the elements are equal

array([[False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [49]:
c1

array([[6, 9, 6, 1],
       [0, 2, 7, 0],
       [8, 3, 6, 8]])

In [50]:
# Sort one of the arrays you just created in ascending order
c1.sort()
c1

array([[1, 6, 6, 9],
       [0, 0, 2, 7],
       [3, 6, 8, 8]])

In [51]:
# Sort the indexes of one of the arrays you just created
np.argsort(c2)

array([[3, 1, 2, 0],
       [2, 0, 1, 3],
       [2, 3, 1, 0]], dtype=int64)

In [52]:
c2

array([[9, 5, 5, 3],
       [7, 9, 5, 9],
       [8, 7, 3, 5]])

In [53]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(c2)

0

In [54]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(c2)

3

In [56]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(c2, axis = 1)

array([0, 1, 0], dtype=int64)

In [57]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(c2, axis = 0)

array([1, 0, 2, 0], dtype=int64)

In [58]:
# Create an array of normally distributed random numbers
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [62]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.